version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: crabflow
      DOCKER_URL: tcp://docker:2375
      LOG_FILTER: debug
      REGISTRY: registry:5000
      WORKFLOWS_DIR: /var/lib/crabflow/workflows/examples
    volumes:
    - workflows-dir:/var/lib/crabflow/workflows
    depends_on:
      docker:
        condition: service_started
      migrator:
        condition: service_completed_successfully
      registry:
        condition: service_started
    profiles: [full]

  docker:
    image: docker:24
    privileged: true
    command:
    - --insecure-registry=registry:5000
    environment:
      DOCKER_TLS_CERTDIR: ''

  git-synchronizer:
    build:
      context: .
      dockerfile: Dockerfile
      target: git-synchronizer
    environment:
      REPOSITORY: https://github.com/leroyguillaume/crabflow
    volumes:
    - workflows-dir:/var/lib/crabflow/workflows
    profiles: [full]

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    environment:
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: crabflow
    depends_on:
      postgres:
        condition: service_started
    profiles: [full]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: crabflow
      POSTGRES_PASSWORD: crabflow
    ports:
    - 5432:5432

  registry:
    image: registry:2
    ports:
    - 5000:5000

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: scheduler
    environment:
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: crabflow
    depends_on:
      migrator:
        condition: service_completed_successfully
    profiles: [full]

volumes:
  workflows-dir:
