CREATE TABLE workflow (
    id VARCHAR (255) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    target VARCHAR (255) NOT NULL UNIQUE,
    image VARCHAR (255) NOT NULL UNIQUE,
    loaded BOOL NOT NULL DEFAULT FALSE
);
