ARG VERSION=bookworm

FROM rust:1-slim-$VERSION AS build

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=target <<EOF /bin/sh -e
cargo build --release
cp -r target/release /build
EOF

{% for target in targets %}
FROM debian:$VERSION-slim AS {{ target }}

COPY --from=build /build/{{ target }} /usr/local/bin/{{ target }}

ENTRYPOINT ["/usr/local/bin/{{ target }}"]
{%endfor %}
