name: build-publish-py

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  pull_request:
  push:
    tags: ['*']

jobs:
  build-py:
    name: build-publish-py
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        cache: pip

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: build
      run: maturin build -F py

    - name: publish
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
      run: maturin publish -F py
