name: publish-release

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  push:
    tags: ['*']

jobs:
  publish-release:
    name: publish-release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --all-features

    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
