name: release

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  push:
    tags: ['*']

jobs:
  crates-io:
    name: crates.io
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --all-features

  pypi:
    name: pypi
    runs-on: ${{ matrix.target.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target:
        - name: aarch64-unknown-linux-gnu
          runs-on: ubuntu-latest
        - name: x86_64-apple-darwin
          runs_on: macos-latest
        - name: x86_64-unknown-linux-gnu
          runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        cache: pip

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: publish
      uses: PyO3/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
      with:
        command: publish
        args: -F py -r
        target: ${{ matrix.target.name }}

  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
