name: test

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: restore rust cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: test_cargo

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        cache: pip

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: test
      run: cargo test --all-features

    - name: run python example
      run: |
        python -m venv venv
        . ./venv/bin/activate
        maturin develop -F py
        python examples/python.py
